"""si

Revision ID: 064b3ba6e23b
Revises: 4693c2bf8cb3
Create Date: 2023-09-22 07:50:27.330728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064b3ba6e23b'
down_revision = '4693c2bf8cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_column('people')
        batch_op.drop_column('genre')
        batch_op.drop_column('date_added')
        batch_op.drop_column('release_date')
        batch_op.drop_column('imdb_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imdb_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('date_added', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('people', sa.TEXT(), nullable=True))
        batch_op.alter_column('rating',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
