"""si

Revision ID: d209e3268a50
Revises: e00e5cd5932e
Create Date: 2023-09-22 09:58:16.905671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd209e3268a50'
down_revision = 'e00e5cd5932e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vidurl', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('imgurl', sa.String(), nullable=True))
        batch_op.drop_column('img_url')
        batch_op.drop_column('vid_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vid_url', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('img_url', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('imgurl')
        batch_op.drop_column('vidurl')

    # ### end Alembic commands ###
