"""si

Revision ID: e00e5cd5932e
Revises: 064b3ba6e23b
Create Date: 2023-09-22 08:13:23.717442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e00e5cd5932e'
down_revision = '064b3ba6e23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vid_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('img_url', sa.String(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_constraint('fk_channels_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_channels_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('img_url')
        batch_op.drop_column('vid_url')

    # ### end Alembic commands ###
